import { encryptJson, decryptJson } from "./oauth";
import { getDb } from "./mongo";

// Additional GitHub accounts linked to a primary account (ADR 0002: linking
// is anchored on real GitHub identity, never on anything generated by the
// MCP client). Each linked account's token is stored encrypted (reusing the
// AES-256-GCM helpers already used by the OAuth flow, in lib/oauth.ts) —
// never in plaintext in the database.

export type LinkedAccount = {
  login: string;
  token: string; // already decrypted when returned by getLinkedAccounts
  linkedAt: string;
};

type LinkedAccountDoc = {
  primaryLogin: string;
  login: string;
  encryptedToken: string;
  linkedAt: string;
};

const COLLECTION = "linked_accounts";

export async function linkAccount(primaryLogin: string, login: string, token: string): Promise<void> {
  const db = await getDb();
  const encryptedToken = encryptJson({ token });
  await db.collection<LinkedAccountDoc>(COLLECTION).updateOne(
    { primaryLogin, login },
    { $set: { primaryLogin, login, encryptedToken, linkedAt: new Date().toISOString() } },
    { upsert: true }
  );
}

export async function getLinkedAccounts(primaryLogin: string): Promise<LinkedAccount[]> {
  const db = await getDb();
  const docs = await db.collection<LinkedAccountDoc>(COLLECTION).find({ primaryLogin }).toArray();
  return docs.map((d) => {
    const { token } = decryptJson<{ token: string }>(d.encryptedToken);
    return { login: d.login, token, linkedAt: d.linkedAt };
  });
}
